unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Fix colors
#set -g default-terminal "tmux-253color"
set -ga terminal-overrides ",*256col*:Tc"

# Split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind-key -n M-Enter split-window -h -c "#{pane_current_path}"
unbind '"'
unbind %

# Switch panes using Alt-arrow without prefix
bind -n M-H select-pane -L
bind -n M-L select-pane -R
bind -n M-J select-pane -U
bind -n M-K select-pane -D


# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -g escape-time 0

# Show messages for 4 seconds
set-option -g display-time 4000

# Reload config
bind R source-file ~/.tmux.conf \; display "Config reloaded!"

# Mouse mouse
setw -g mouse on

# Status bar
set -g status-style bg=default
set -g status-left ' '
set -g status-right ' '
set -g status-justify absolute-centre
set -g window-status-current-format "#[bg=#272727] #I: #W #[default]"
set -g window-status-format ' #I: #W '
set -g focus-events on

bind -n M-r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# Use Alt + s to move pane to a new window
bind -n M-s break-pane

# Use Alt + Q to close current pane
bind -n M-q kill-pane

# Use Alt + s to move pane to a new window
bind -n M-s break-pane

# Use Alt + Q to close current pane
bind -n M-q kill-pane

# Use Alt + N to create a new window
bind -n M-n new-window -c "#{pane_current_path}"

# Left status bar text
#set -g status-left ' '

# Right status bar length
set -g status-right-length 80

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n m-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5

bind-key c copy-mode

set-option -g renumber-windows on

bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

