#!/usr/bin/env bash

# Quick shortcuts to some dirs
alias dls="cd ~/downloads"
alias docs="cd ~/documents"
alias prjs="cd ~/projects"
alias pics="cd ~/pictures"
alias conf="cd ~/.config"
alias vids="cd ~/videos"
alias dots="cd ~/dotfiles"
alias bin="cd ~/bin"
alias lbin="cd $HOME/.local/bin"
alias tmp="cd /tmp"
alias shots="cd ~/pictures/screenshots"
alias ..="cd .."

# Quickly edit some files
alias zshrc="nvim $HOME/.zshrc && source $HOME/.zshrc"
alias aliases="nvim $HOME/.config/aliases && source $HOME/.config/aliases"
alias i3config="nvim $HOME/.config/i3/config"
alias vimrc="nvim ~/.config/nvim/init.lua"
alias vifmrc="nvim $HOME/.config/vifm/vifmrc"

# Enable colors for some commands
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias tree="tree -C"
alias diff="diff --color"
alias ip="ip -c=always"

# Use 'eza' instead of 'ls'
alias ls="eza"
alias ll='eza -alF'
alias la='eza -a'
alias l='eza -CF'

# Basically, lets me know what just happened
# --interactive     prompt before overwrite
# --verbose         explain what is being done
alias cp="cp --interactive --verbose"
alias mv="mv --interactive --verbose"
alias rm="rm --verbose"

# Aliases to prevent leaving junk in $HOME
alias feh="feh --no-fehbg"
alias mitmproxy="mitmproxy --set confdir=$XDG_CONFIG_HOME/mitmproxy"                             
alias mitmweb="mitmweb --set confdir=$XDG_CONFIG_HOME/mitmproxy"
alias wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts"
alias svn="svn --config-dir $XDG_CONFIG_HOME/subversion"
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'

# Dont show the annoying banner in ipython3
alias ipython3="ipython3 --no-banner"

# Old habits and typos
alias vim="nvim"
alias vi="nvim"
alias v="nvim"

# [R]aw ViM
# Open vim with default config
alias rvim="nvim -u NONE"
alias rvi="nvim -u NONE"

# The remaining storage
alias storage="df -h $HOME --output=avail | tail -1 | xargs echo | sed 's/G/ GB/g'"

# cat, but with syntax highlighting
alias cat="bat --theme base16 -p"

# https://www.ostechnix.com/youtube-dl-tutorial-with-ezamples-for-beginners/
alias ytdl="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'"

alias gif2mp4='ffmpeg -i $1 -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" $2'

# Some git aliases
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gs="git status"
alias gd="git diff"

# Some tmux aliases
alias tl='tmux list-sessions'
alias tk="tmux kill-session -t tmux list-sessions | fzf | cut -d ':' -f1"
alias td='tmux detach'

# Quickly blend in with the public by using a light terminal theme.
# I always get strange looks if Im using the terminal in public with dark colors
alias blend="wal -l -i $HOME/pictures/current/*"

# Launch vifm using vifmrun so that I can have file previews
alias vifm="vifmrun"

# Packages I Installed
alias pii="comm -23 <(pacman -Qqett | sort) <(pacman -Qqg base -g base-devel | sort | uniq)"

# Start a simple http server
alias pyserver="python3 -m http.server"

# Upload python project to pypi
alias pyup="python3 setup.py sdist && python3 -m twine upload dist/*"

# Open my todo list
alias todo="notes && vim todo"

# Kitty terminal tends to have issues with the "clear" command it's terminfo files
# are not available on the server. The alias below fixes it.
#alias ssh="kitty +kitten ssh"

# Launch jupyter notebook
alias jn="jupyter notebook"

# [J]ust [P]ush
# Sometimes I just need to push the code and dont care about
# the commit message
# git rev-parse --show-toplevel
alias jp="git add . && git commit -m \"$(date)\" && git push"

# Much quicker to just run 'o' instead of
# typing out the whole command 
alias o="open"

# A nmap alias that makes me go woah!makes me go woah!
alias woah="nmap -sC -sV -A -Pn"

# Launch fontpreview
alias fp="fontpreview-ueberzug -b #1d1f21 -f #c5c8c6"

alias se="sudoedit"

# Incognito mode. Useful for when some commands must have secrets through the command
alias anon="export HISTFILE='' && echo 'Incognito mode activated'"

# Connect to TryHackMe VPN
alias thm="sudo openvpn ~/documents/sdushantha.ovpn"

# Get TryHackMe machine IP
alias thmip="ip -o -4 addr show dev tun0 | awk '{print $4}' | cut -d/ -f1 | tr -d '[:space:]'"

# Disable splash screen for Sonic Visualiser as its annoying
alias sonic-visualiser="sonic-visualiser --no-splash"
