#!/usr/bin/env bash

# Quick shortcuts to some dirs
alias dls="cd ~/downloads"
alias docs="cd ~/documents"
alias prjs="cd ~/projects"
alias pics="cd ~/pictures"
alias conf="cd ~/.config"
alias vids="cd ~/videos"
alias dots="cd ~/dotfiles"
alias bin="cd ~/bin"
alias lbin="cd $HOME/.local/bin"
alias tmp="cd /tmp"
alias shots="cd ~/pictures/screenshots"
alias notes="cd ~/documents/notes"
alias ..="cd .."

# Quickly edit some files
alias zshrc="nvim $HOME/.zshrc && source $HOME/.zshrc"
alias aliases="nvim $HOME/.config/aliases && source $HOME/.config/aliases"
alias i3config="nvim $HOME/.config/i3/config"
alias vimrc="nvim ~/.config/nvim/init.vim"
alias vifmrc="nvim $HOME/.config/vifm/vifmrc"
alias binds="nvim $HOME/.config/sxhkd/sxhkdrc"

# Enable colors for some commands
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias tree="tree -C"

# Some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Dont show the annoying banner in ipython3
alias ipython3="ipython3 --no-banner"

# I prefer neovim, but I am used to typing vim
alias vim="nvim"

# The remaining storage
alias storage="df -h / --output=avail | tail -1 | xargs echo | sed 's/G/ GB/g'"

# cat, but with syntax highlighting and it is automaticaly piped to less if 
# the whole text does not fit in in the terminal
alias cat="bat -p"

# https://www.ostechnix.com/youtube-dl-tutorial-with-examples-for-beginners/
alias ytdl="youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'"

alias gif2mp4='ffmpeg -i $1 -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" $2'

# Some git aliases
alias gadd="git add"
alias gclone="git clone"
alias gcommit="git commit"
alias gpush="git push"
alias gstatus="git status"

alias mail="aerc"

# Quickly blend in with the public by using a light terminal theme.
# I always get strange looks if Im using the terminal in public with dark colors
alias blend="wal -l -i $HOME/pictures/current/*"

# Launch vifm using vifmrun so that I can have file previews
alias vifm="vifmrun"

# Packages I Installed
alias pii="comm -23 <(pacman -Qqett | sort) <(pacman -Qqg base -g base-devel | sort | uniq)"

# Start a simple http server
alias pyserver="python3 -m http.server"

# Upload python project to pypi
alias pyup="python3 setup.py sdist && python3 -m twine upload dist/*"

# Basically, lets me know what just happened
# --interactive     prompt before overwrite
# --verbose         explain what is being done
alias cp="cp --interactive --verbose"
alias mv="mv --interactive --verbose"
alias rm="rm --verbose"
