#!/usr/bin/env python3

from time import sleep
from os import system
import sys

MINUTES = 1
# Turn the min into sec
TIME = MINUTES * 60 
UBUNTU_NOTIF = 'notify-send "Time to stand! Stand up and move a little for a minute or two,"'


def start(time, notification):
	print("Sitting down for longer than 30 min cause damage")
	sleep(time)
	system(notification)
	sys.exit()

start(TIME, UBUNTU_NOTIF)
